version: '3.8'

services:

    postgres-database:
            image: postgres:13.1-alpine
            container_name: postgres-database
            restart: always
            env_file:
                - ../config/database.env
            environment:
                PGDATA: /var/lib/postgresql/data
            volumes:
                - ../pgdata/:/var/lib/postgresql/data
            ports:
                - 5432:5432

    le-bot-en-js:
        image: tanguychiffoleau/le-bot-en-js:latest
        container_name: le-bot-en-js
        depends_on:
            - postgres-database
        restart: on-failure
        env_file:
            - ../config/bot.env
        volumes:
            - ../config/reactionRoleConfig.json:/usr/src/app/config/reactionRoleConfig.json
